-- 세미 프로젝트 계정 생성
CREATE USER JEONGBA IDENTIFIED BY JEONGBA;
GRANT RESOURCE, CONNECT TO JEONGBA;

--시스템 계정으로 할것
GRANT CREATE VIEW TO JEONGBA;

-- 테이블 스페이스 권한 부여
-- GRANT UNLIMITED TABLESPACE TO JEONGBA;